### ISSUE TITLE
生成不了数据库

### ISSUE THREAD

**Issue by cicna** [geffzhang/NanoFabric-ServiceFabric#7]
Enable-Migrations -EnableAutomaticMigrations
Add-Migration InitialCreate
Update-Database -Verbose

报错
在“LTMCompanyNameFree.YoyoCmsTemplate.Migrator”下报：
No DbContext was found in assembly 'LTMCompanyNameFree.YoyoCmsTemplate.Migrator'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.

在“LTMCompanyNameFree.YoyoCmsTemplate.EntityFrameworkCore”下报：
Could not find content root folder!

**Comment by cicna** [comment]
System.Exception: Could not find content root folder!
   at LTMCompanyNameFree.YoyoCmsTemplate.Web.WebContentDirectoryFinder.CalculateContentRootFolder() in D:\Git\NanoFabric-ServiceFabric\52ABP\LTMCompanyNameFree.YoyoCmsTemplate.Core\Web\WebContentFolderHelper.cs:line 30
   at LTMCompanyNameFree.YoyoCmsTemplate.EntityFrameworkCore.YoyoCmsTemplateDbContextFactory.CreateDbContext(String[] args) in D:\Git\NanoFabric-ServiceFabric\52ABP\LTMCompanyNameFree.YoyoCmsTemplate.EntityFrameworkCore\EntityFrameworkCore\YoyoCmsTemplateDbContextFactory.cs:line 15
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)

**Comment by ESiangChioa** [comment]
就冲52abp默认只支持mssql 放弃学习了。
